services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: leadwiesel2
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.postgresql:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432
